/**
 * Zweisprachiges (DE / EN) Vokabular für den regelbasierten Rezept-Parser.
 * Zentral konfigurierbar und gepflegt.
 */

export interface LanguageVocab {
  // Marker für Zutaten-Abschnitte
  ingredientMarkers: string[];
  // Marker für Zubereitungs-Abschnitte
  stepMarkers: string[];
  // Emojis, die Abschnitte einleiten
  ingredientEmojis: string[];
  stepEmojis: string[];
  // Unterüberschriften innerhalb von Zutaten (dürfen NICHT zu Zubereitung wechseln!)
  subIngredientPrefixes: string[];
  // Verben, die typisch am Beginn von Zubereitungsschritten stehen (Imperativ & Infinitiv)
  stepVerbs: string[];
  // Füllwörter / Zeitwörter für Abfolgen
  sequenceWords: string[];
  // Outro / CTA / Social-Media-Müll (wird zu 'sonstiges')
  outroKeywords: string[];
}

export const VOCABULARY: Record<"de" | "en", LanguageVocab> = {
  de: {
    ingredientMarkers: [
      "zutaten",
      "zutat",
      "wir brauchen",
      "du brauchst",
      "du benötigst",
      "das brauchst du",
      "dafür brauchst du",
      "das benötigst du",
      "einkaufsliste",
      "was du brauchst",
      "was ihr braucht",
    ],
    stepMarkers: [
      "zubereitung",
      "anleitung",
      "so gehts",
      "so geht's",
      "so wird's gemacht",
      "so geht es",
      "vorgehensweise",
      "schritte",
      "schritt für schritt",
      "machen",
      "zubereiten",
      "anweisung",
    ],
    ingredientEmojis: ["🛒", "🥣", "🥗"],
    stepEmojis: ["👩‍🍳", "👨‍🍳", "📝"],
    subIngredientPrefixes: [
      "für den teig",
      "für die soße",
      "für die sauce",
      "für die füllung",
      "für das dressing",
      "für die marinade",
      "für die creme",
      "für das topping",
      "für den boden",
      "für die kruste",
      "für die glasur",
      "für den guss",
      "für das frosting",
      "für den salat",
      "für das gemüse",
      "zum garnieren",
      "außerdem",
      "gewürze",
      "topping",
      "dressing",
      "marinade",
      "deko",
    ],
    stepVerbs: [
      "erhitze",
      "erhitzen",
      "schneide",
      "schneiden",
      "brate",
      "braten",
      "anbraten",
      "anrösten",
      "koche",
      "kochen",
      "aufkochen",
      "backe",
      "backen",
      "rühre",
      "rühren",
      "verrühren",
      "umrühren",
      "unterrühren",
      "unterheben",
      "mische",
      "mischen",
      "vermenge",
      "vermengen",
      "gebe",
      "geben",
      "dazugeben",
      "hinzugeben",
      "würze",
      "würzen",
      "salzen",
      "pfeffern",
      "abschmecken",
      "schmecke",
      "stelle",
      "stellen",
      "gieße",
      "gießen",
      "abgießen",
      "wasche",
      "waschen",
      "schäle",
      "schälen",
      "püriere",
      "pürieren",
      "forme",
      "formen",
      "belege",
      "belegen",
      "bestreichen",
      "einrollen",
      "verteile",
      "verteilen",
      "streue",
      "streuen",
      "ziehe",
      "ziehen",
      "lassen",
      "köcheln",
      "dünsten",
      "schwenken",
      "ausrollen",
      "kneten",
      "schlagen",
      "aufschlagen",
      "beträufeln",
      "einfetten",
      "schmelzen",
      "zerlasse",
      "zerlassen",
      "hobeln",
      "hobel",
      "hacken",
      "hacke",
      "zerdrücken",
      "zerdrücke",
      "garnieren",
      "anrichten",
    ],
    sequenceWords: [
      "zuerst",
      "dann",
      "danach",
      "anschließend",
      "zuletzt",
      "als nächstes",
      "währenddessen",
      "zum schluss",
      "jetzt",
      "nun",
      "nachdem",
    ],
    outroKeywords: [
      "folge mir",
      "folgt mir",
      "abonnieren",
      "speichere das rezept",
      "rezept speichern",
      "speichern nicht vergessen",
      "guten appetit",
      "lass es dir schmecken",
      "viel spaß beim nachkochen",
      "link in bio",
      "kommentiere",
      "rezept in den kommentaren",
      "tarif yorumlarda",
      "nährwerte",
      "nutrition",
      "kalorien",
      "kcal",
      "notizen",
      "tipps",
      "hinweise",
    ],
  },
  en: {
    ingredientMarkers: [
      "ingredients",
      "ingredient",
      "what you need",
      "you will need",
      "you need",
      "you'll need",
      "what you'll need",
      "grocery list",
      "shopping list",
    ],
    stepMarkers: [
      "instructions",
      "instruction",
      "directions",
      "method",
      "preparation",
      "how to make",
      "how to make it",
      "steps",
      "step by step",
    ],
    ingredientEmojis: ["🛒", "🥣", "🥗"],
    stepEmojis: ["👩‍🍳", "👨‍🍳", "📝"],
    subIngredientPrefixes: [
      "for the dough",
      "for the sauce",
      "for the filling",
      "for the dressing",
      "for the marinade",
      "for the topping",
      "for the crust",
      "for the base",
      "for the batter",
      "for the frosting",
      "for the glaze",
      "for the salad",
      "to garnish",
      "optional",
      "spices",
      "topping",
      "dressing",
      "marinade",
      "garnish",
    ],
    stepVerbs: [
      "heat",
      "preheat",
      "cut",
      "chop",
      "dice",
      "slice",
      "fry",
      "pan-fry",
      "stir-fry",
      "cook",
      "boil",
      "simmer",
      "bake",
      "roast",
      "stir",
      "mix",
      "blend",
      "combine",
      "whisk",
      "fold",
      "toss",
      "layer",
      "drizzle",
      "bring",
      "roll",
      "flip",
      "toast",
      "steam",
      "chill",
      "cover",
      "add",
      "pour",
      "drain",
      "season",
      "wash",
      "rinse",
      "peel",
      "mash",
      "spread",
      "place",
      "put",
      "set",
      "sprinkle",
      "garnish",
      "serve",
      "let",
      "cool",
      "melt",
      "crush",
    ],
    sequenceWords: [
      "first",
      "then",
      "next",
      "after",
      "afterwards",
      "meanwhile",
      "finally",
      "lastly",
      "now",
      "once",
    ],
    outroKeywords: [
      "follow for more",
      "follow me",
      "save for later",
      "save this recipe",
      "don't forget to save",
      "enjoy",
      "bon appetit",
      "link in bio",
      "comment below",
      "recipe in comments",
      "nutrition",
      "calories",
      "macros",
      "notes",
      "tips",
    ],
  },
};

const ALL_VOCAB = {
  ingredientMarkers: [
    ...VOCABULARY.de.ingredientMarkers,
    ...VOCABULARY.en.ingredientMarkers,
  ],
  stepMarkers: [
    ...VOCABULARY.de.stepMarkers,
    ...VOCABULARY.en.stepMarkers,
  ],
  ingredientEmojis: [
    ...VOCABULARY.de.ingredientEmojis,
    ...VOCABULARY.en.ingredientEmojis,
  ],
  stepEmojis: [
    ...VOCABULARY.de.stepEmojis,
    ...VOCABULARY.en.stepEmojis,
  ],
  subIngredientPrefixes: [
    ...VOCABULARY.de.subIngredientPrefixes,
    ...VOCABULARY.en.subIngredientPrefixes,
  ],
  stepVerbs: [
    ...VOCABULARY.de.stepVerbs,
    ...VOCABULARY.en.stepVerbs,
  ],
  sequenceWords: [
    ...VOCABULARY.de.sequenceWords,
    ...VOCABULARY.en.sequenceWords,
  ],
  outroKeywords: [
    ...VOCABULARY.de.outroKeywords,
    ...VOCABULARY.en.outroKeywords,
  ],
};

/** Hilfsfunktion: Gibt alle Keywords beider Sprachen vereint zurück */
export function getAllVocab() {
  return ALL_VOCAB;
}
